services:
  produtos.api:
    image: ${DOCKER_REGISTRY-}produtosapi
    container_name: Product.Api
    build:
      context: .
      dockerfile: Produtos.Api/Dockerfile
    depends_on:
      - product-db
      - product-blob
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - product-network

  product-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: Product.Db
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - product-network

  product-blob:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: Product.Blob
    ports:
      - "10000:10000" # Blob Storage
    networks:
      - product-network

networks:
  product-network:
    driver: bridge
